[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tinymap"
dynamic = ["version"]
dependencies = [
    "click", 
    "rich"
]
requires-python = ">= 3.12"

[project.scripts]
tmap = "tinymap.cli:main"